environments:
  dev:
    kubeContext: gke-lr-dev
  stg:
    kubeContext: gke-lr-stg
  test:
    kubeContext: gke-lr-test
  demo:
    kubeContext: gke-lr-demo
  prd:
    kubeContext: gke-lr-prd
  bastion-prd:
    kubeContext: gke-lr-bastion-prd
  bastion-non-prd:
    kubeContext: gke-lr-bastion-non-prd