apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-v2
  labels:
    dashboards: "grafana"
spec:
  version: "11.6.3"
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: root
      admin_password: secret