# Need to declare bases in top and bottom layers
bases:
  - environments.yaml
  - charts/repos.yaml  
---
templates:
  default:
    missingFileHandler: Warn
    values:
    - configs/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}/values.yaml
    - configs/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}/values.yaml
    secrets:
    - configs/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}/secrets.yaml
    - configs/{{`{{ .Release.Namespace }}`}}/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}/secrets.yaml
---
helmDefaults:
  diffArgs:
    # - "--show-secrets"
    - "--context=3"
  skipDeps: false
  createNamespace: false
  historyMax: 5
---
releases:
  - name: istio-base
    namespace: istio-system
    chart: istio/base
    version: 1.25.0
    inherit:
    - template: default

  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    version: 1.25.0
    inherit:
    - template: default

  - name: istio-ingressgateway
    namespace: istio-system
    chart: istio/gateway
    version: 1.24.6
    inherit:
    - template: default

  - name: prometheus-blackbox-exporter
    namespace: observability-client
    chart: prometheus-community/prometheus-blackbox-exporter
    version: 9.5.0
    inherit:
    - template: default
