replicas: 2
mode: distributed
persistence:
  enabled: true
  size: 50Gi
rootUser: rootuser
rootPassword: rootpass123
buckets:
  - name: pgo-backup
    policy: none
resources:
  requests:
    memory: 500Mi
    cpu: 500m
  limits:
    memory: 6Gi
    cpu: 2