        - annotations:
            summary: Redis is down for the last 5 minutes.
          condition: C
          data:
            - datasourceUid: beienpsdcdce8b
              model:
                disableTextWrap: false
                editorMode: code
                expr: redis_up == bool 0
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
              refId: A
              relativeTimeRange:
                from: 600
            - datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
              refId: C
              relativeTimeRange: {}
          execErrState: Error
          folderUID: fen97rev6xp8ga
          for: 5m0s
          id: 65
          labels:
            owner: IT Operations
            priority: P0
          noDataState: NoData
          orgID: 1
          ruleGroup: 1m
          title: RedisDown
          uid: fepxzpukzyu4ga
          updated: "2025-06-26T06:30:19.000Z"