repositories:
  - name: bitnami
    url: registry-1.docker.io/bitnamicharts
    oci: true
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: gitlab
    url: https://charts.gitlab.io
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: runix
    url: https://helm.runix.net
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard
  - name: wazuh
    url: https://morgoved.github.io/wazuh-helm/    