repositories:
  - name: bitnami
    url: registry-1.docker.io/bitnamicharts
    oci: true
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: gitlab
    url: https://charts.gitlab.io
