apiVersion: 1
groups:
{{- range $provision := .Values.grafana.provision.datasources.tenantList -}}
{{ $orgId := $provision.orgId }}
  - folder: {{ printf "%s" $orgId }}
    interval: 1m
    name: Kubernetes Apps
    orgId: 1
    rules:
      - title: KubePodNotReady
        uid: {{ printf "KubePodNotReady-%s" $orgId | trunc 40 }}
        annotations:
          summary: "Pod {{`{{ $labels.namespace }}`}} / {{`{{ $labels.pod }}`}} has been in a non-ready state for longer than 15 minutes"
          description: "Pod has been in a non-ready state for more than 15 minutes"
        condition: A
        data:
          - datasourceUid: {{ printf "metrics-%s" $orgId }}
            model:
              datasource:
                type: prometheus
                uid: {{ printf "metrics-%s" $orgId }}
              editorMode: code
              expr: 'sum by (namespace, pod, cluster) (max by (namespace, pod, cluster) (kube_pod_status_phase{job="kube-state-metrics",namespace=~".*",phase=~"Pending|Unknown|Failed"}) * on (namespace, pod, cluster) group_left (owner_kind) topk by (namespace, pod, cluster) (1, max by (namespace, pod, owner_kind, cluster) (kube_pod_owner{owner_kind!="Job"}))) '
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
            refId: A
            relativeTimeRange:
              from: 600
              to: 0
          - datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold
            refId: B
        execErrState: Error
        for: 15m
        isPaused: false
        labels: {}
        noDataState: OK
      - title: KubeNodeNotReady
        uid: {{ printf "KubeNodeNotReady-%s" $orgId | trunc 40 }}
        annotations:
          summary: "{{`{{ $labels.node }}`}} has been unready for more than 15 minutes"
          description: "Node has been unready for more than 15 minutes"
        condition: B
        data:
          - datasourceUid: {{ printf "metrics-%s" $orgId }}
            model:
              datasource:
                type: prometheus
                uid: {{ printf "metrics-%s" $orgId }}
              editorMode: code
              expr: kube_node_status_condition{condition="Ready",job="kube-state-metrics",status="true"} == 0
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
            refId: A
            relativeTimeRange:
              from: 600
              to: 0
          - datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold
            refId: B
            relativeTimeRange:
              from: 600
              to: 0
        execErrState: Error
        for: 15m
        isPaused: false
        labels: {}
        noDataState: OK
      - title: KubePodCrashLooping
        uid: {{ printf "KubePodCrashLooping-%s" $orgId | trunc 40 }}
        annotations:
          summary: "pod/ {{`{{ $labels.pod }}`}} in namespace {{`{{ $labels.namespace }}`}} has been in CrashLoopBackOff state for longer than 5 minutes"
          description: "Pod is crash looping for more than 5 minutes"
        condition: B
        data:
          - datasourceUid: {{ printf "metrics-%s" $orgId }}
            model:
              datasource:
                type: prometheus
                uid: {{ printf "metrics-%s" $orgId }}
              editorMode: code
              expr: max_over_time(kube_pod_container_status_waiting_reason{job="kube-state-metrics",namespace=~".*",reason="CrashLoopBackOff"}[5m]) >= 1
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
            refId: A
            relativeTimeRange:
              from: 600
              to: 0
          - datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: threshold
            refId: B
            relativeTimeRange:
              from: 600
              to: 0
        execErrState: Error
        for: 5m
        isPaused: false
        labels: {}
        noDataState: OK
{{- end }}