rules:
  - uid: KashaServiceNotReady
    title: KashaServiceNotReady
    condition: B
    query:
      datasource:
        type: prometheus
      expr: kasha_service_health
      timeRange:
        from: 600
        to: 0
    threshold:
      operator: lt
      value: 1
    for: 5m
    annotations:
      summary: "Kasha service is not ready after 5 minutes."
    labels:
      owner: "Developement Team"
      priority: "P0"
    isPaused: true